AWSTemplateFormatVersion: "2025-09-25"
Description: "TTH Inventory Management - DynamoDB"

Parameters:
 Env:
  Type: String
 KMSOrganizationsKeyId:
  Type: String

Resources:
 # DynamoDB Table
 # -------------------------------------------------------------
 ProductsTable:
  DeletionPolicy: Retain
  Type: AWS::DynamoDB::Table
  Properties:
   TableName: "Products"
   AttributeDefinitions:
    -
     AttributeName: "InstitutionCode"
     AttributeType: "S"
    -
     AttributeName: "ProductId"
     AttributeType: "S"
    -
     AttributeName: "ProductName"
     AttributeType: "S"
   KeySchema: 
    -
     AttributeName: "InstitutionCode"
     KeyType: "HASH"
    -
     AttributeName: "ProductId"
     KeyType: "RANGE"
   GlobalSecondaryIndexes: 
    -
     IndexName: CreateDateTime-index
     KeySchema: 
      -
        AttributeName: "InstitutionCode"
        KeyType: "HASH"
      -
        AttributeName: "ProductName"
        KeyType: "RANGE"
     Projection: 
        ProjectionType: "ALL"
   BillingMode: "PAY_PER_REQUEST"
   PointInTimeRecoverySpecification: 
    PointInTimeRecoveryEnabled: true
   SSESpecification: 
    SSEEnabled: false
   TableClass: "STANDARD"
   TimeToLiveSpecification:
    AttributeName: ExpirationTime
    Enabled: true